version: "3.9"
services:
  go-migrate-sample-api:
    depends_on:
      - go-migrate-sample-db
    ports:
      - 8080:80
    build:
      context: .
      target: debug
    restart: always
    container_name: "go-migrate-sample-api"
    networks:
      - go-migrate-sampleNet
    env_file: .env
    volumes:
      - .:/root/api
    tty: true

  go-migrate-sample-db:
    image: postgres:14-alpine
    restart: unless-stopped
    container_name: "go-migrate-sample-db"
    ports:
      - 15432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - go-migrate-sampleNet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      timeout: 20s
      interval: 3s
      retries: 10

  go-migrate-sample-db-migration:
    depends_on:
      go-migrate-sample-db:
        condition: service_healthy
    build:
      context: db-migration
    container_name: go-migrate-sample-db-migration
    networks:
      - go-migrate-sampleNet
    environment:
      DB_HOST: go-migrate-sample-db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db-migration:/root/migration
    entrypoint: ["/bin/sh", "scripts/migrate_local.sh"]
    command: up

networks:
  go-migrate-sampleNet:

volumes:
  db-data:
